name:                haskell-clean-architecture
version:             0.1.0.0
github:              "Github username here/real-world-app"
license:             GPL-3
author:              "Author name here"
maintainer:          "Author email here"
copyright:           "2019 Author name here"

extra-source-files:
  - README.md

description:         Please see the README on GitHub at <https://github.com/err0r500/haskell-clean-architecture#readme>

dependencies:
  - base >= 4.7 && < 5
  - rio >= 0.1.15.0 && < 0.2
  - data-has

  # the logger
  - katip >= 0.8.4.0

  # the http server, may be replaced by servant
  - aeson

  - scotty
  - wai
  - wai-extra
  - warp
  - http-types

  - servant-server == 0.17
  - mtl

  # storage
  - hasql == 1.4.2
  - hasql-th >= 0.4.0.6

  # various
  - uuid
  - email-validate

default-extensions:
  - NoImplicitPrelude
  - OverloadedStrings
  - ConstraintKinds
  - FlexibleContexts
  - GeneralizedNewtypeDeriving
  - RankNTypes
  - MonoLocalBinds

library:
  source-dirs: src
  ghc-options:
    - -Wall

executables:
  haskell-clean-architecture-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - haskell-clean-architecture

tests:
  haskell-clean-architecture-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - haskell-clean-architecture
      - hspec-discover
      - hspec
      - hspec-wai
      - hspec-wai-json
      - interpolatedstring-perl6 == 1.0.2
